"""
backend/utils/file_storage.py
==============================
Filesystem helpers for persisting uploaded contract files.

All I/O is done synchronously (using ``aiofiles`` is optional), since the
FastAPI endpoints call these helpers inside ``run_in_executor`` or at service
layer — keeping the async boundary clean.

Storage layout
--------------
::

    storage/
    └── contracts/
        ├── <uuid>_<original_filename>.pdf
        └── <uuid>_<original_filename>.docx
"""

from __future__ import annotations

import uuid
from pathlib import Path

from backend.config import ALLOWED_EXTENSIONS, STORAGE_DIR
from backend.utils.logger import get_logger

logger = get_logger(__name__)


def ensure_storage_dir() -> None:
    """
    Create the contract storage directory if it does not already exist.

    Called once at application startup in ``main.py``.
    """
    STORAGE_DIR.mkdir(parents=True, exist_ok=True)
    logger.info("Storage directory ready: %s", STORAGE_DIR)


def validate_extension(filename: str) -> bool:
    """
    Return ``True`` if the file has an allowed extension.

    Parameters
    ----------
    filename : str
        Original filename submitted by the client.

    Returns
    -------
    bool
    """
    suffix = Path(filename).suffix.lower()
    return suffix in ALLOWED_EXTENSIONS


def generate_contract_id() -> str:
    """
    Generate a URL-safe UUID4 string to uniquely identify an uploaded contract.

    Returns
    -------
    str
        32-character hex UUID string (no hyphens), e.g. ``"8b31f9a2…"``.
    """
    return uuid.uuid4().hex


def build_file_path(contract_id: str, original_filename: str) -> Path:
    """
    Construct the full filesystem path for a stored contract file.

    The path follows the pattern::

        <STORAGE_DIR>/<contract_id>_<original_filename>

    Parameters
    ----------
    contract_id : str
        UUID hex string generated by :func:`generate_contract_id`.
    original_filename : str
        The client-supplied filename (sanitised before use).

    Returns
    -------
    Path
        Absolute path where the file will be saved.
    """
    # Sanitise the original filename to prevent path traversal
    safe_name = Path(original_filename).name
    return STORAGE_DIR / f"{contract_id}_{safe_name}"


def save_uploaded_file(contract_id: str, filename: str, content: bytes) -> Path:
    """
    Write raw bytes to the contract storage directory.

    Parameters
    ----------
    contract_id : str
        UUID for this upload.
    filename : str
        Original filename (used to preserve the file extension).
    content : bytes
        Raw file bytes read from the upload stream.

    Returns
    -------
    Path
        The absolute path of the saved file.

    Raises
    ------
    OSError
        If the file cannot be written to disk.
    """
    file_path = build_file_path(contract_id, filename)
    file_path.write_bytes(content)
    logger.info("Saved contract %s → %s (%d bytes)", contract_id, file_path, len(content))
    return file_path


def delete_contract_file(file_path: str | Path) -> None:
    """
    Delete a stored contract file.  Silently ignores missing files.

    Parameters
    ----------
    file_path : str | Path
        Absolute path returned by :func:`save_uploaded_file`.
    """
    path = Path(file_path)
    if path.exists():
        path.unlink()
        logger.info("Deleted contract file: %s", path)
    else:
        logger.warning("Attempted to delete non-existent file: %s", path)
